# Generated by Django 5.0.4 on 2024-04-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_orderdetails_orderproductsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('N', 'Not active')], default='A', max_length=20),
            preserve_default=False,
        ),
    ]
