# Generated by Django 5.0.4 on 2024-04-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_storage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriers',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('N', 'Not active')], default='A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='courier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.couriers'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('R', 'Received'), ('D', 'Out for Delivery'), ('C', 'Delivered'), ('X', 'Cancelled')], default='R', max_length=10),
        ),
    ]
