# Generated by Django 5.0.4 on 2024-04-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_couriers_status_alter_orders_courier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='courier',
            field=models.ForeignKey(choices=[('default_courier', 'default_courier default_courier')], on_delete=django.db.models.deletion.PROTECT, to='main_app.couriers'),
        ),
    ]
