# Generated by Django 5.0.4 on 2024-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_orders_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductsdetails',
            name='sell_price_per_kilo',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10),
            preserve_default=False,
        ),
    ]
